FROM node:14 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --silent && \
    npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]