FROM node:14 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . ./
RUN npm run build

FROM node:14
WORKDIR /app
COPY --from=build /app/build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
EXPOSE 5000
CMD ["npm","run","prod"]