FROM node:14 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --silent
COPY . ./
RUN npm run build

FROM node:14
WORKDIR /app
COPY --from=build /app/build /node_modules package.json package-lock.json ./
EXPOSE 5000
CMD ["npm","run","prod"]