apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      imagePullSecrets:
      - name: github-registry
      containers:
      - name: {{ .Values.name}}
        image: {{ .Values.image.name}}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.exposedPort}}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.exposedPort}}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 30
        resources:
          requests:
            memory: {{ .Values.resources.request.memory}}
            cpu: {{ .Values.resources.request.cpu}}
          limits:
            memory: {{ .Values.resources.limits.memory}}
            cpu: {{ .Values.resources.limits.cpu}}
        env:
        - name: "APP_NAME"
          value: {{ .Values.name}}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: {{ .Values.name}}
          containerPort: {{ .Values.exposedPort}}
        - name: {{ .Values.name}}
          containerPort: {{ .Values.exposedPort}}
          
---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name}}
spec:
  minAvailable: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.name}}

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name}}
  ports:
  - protocol: TCP
    name: {{ .Values.name}}
    port: {{ .Values.exposedPort}}
    targetPort: {{ .Values.exposedPort}}
  - protocol: TCP
    name: {{ .Values.name}}
    port: {{ .Values.exposedPort}}
    targetPort: {{ .Values.exposedPort}}
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name}}
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.host}}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: {{ .Values.name}}
      port: {{ .Values.exposedPort}}
  - match: Host(`{{ .Values.host}}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: {{ .Values.name}}
      port: {{ .Values.exposedPort}}
  tls:
    certResolver: default
    options: {}
    