apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret}}
      containers:
      - name: {{ .Values.name}}
        image: {{ .Values.image.name}}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.exposedPort}}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.exposedPort}}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 30
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "1"
        env:
        - name: "APP_NAME"
          value: {{ .Values.name}}
        - name: "PORT"
          value: {{ .Values.exposedPort | quote}}
        - name: "CORS_ENABLED_SITES"
          value: {{ .Values.corsEnabledSites}}
        - name: "MQTT_USER"
          value: {{ .Values.mqtt.username}}
        - name: "MQTT_PASS"
          value: {{ .Values.mqtt.password}}
        - name: "MQTT_CA"
          value: {{ .Values.mqtt.caCert}}
        - name: "MQTT_CLIENT_CERT"
          value: {{ .Values.mqtt.clientCert}}
        - name: "MQTT_CLIENT_KEY"
          value: {{ .Values.mqtt.clientKey}}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: {{ .Values.name}}-d
          containerPort: {{ .Values.exposedPort}}
          
---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name}}
spec:
  minAvailable: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.name}}

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name}}
  ports:
  - protocol: TCP
    name: {{ .Values.name}}-s
    port: {{ .Values.exposedPort}}
    targetPort: {{ .Values.exposedPort}}