name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} 
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/greedhub/utn-ads-2021-frontend:latest
          context: ./frontend
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        uses: azure/setup-helm@v1
        id: install
      - 
        name: 'Deploy'
        run: cd ./frontend/helm-chart && helm upgrade -i --force ads-frontend -f values.yaml ./
        env: 
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'