name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  frontend:
    runs-on: self-hosted
    permissions:
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders-f
      - 
        name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders-f
      -
        name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/greedhub/utn-ads-2021-frontend:latest
          context: ./frontend
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        name: Install Helm
        uses: azure/setup-helm@v1
        id: install
        with:
          version: 3.1.3
      - 
        name: 'Apply Kubeconfig'
        run: mkdir -p $HOME/.kube && echo ${{ secrets.KUBECONFIG }} | base64 -d > $HOME/.kube/config 
      -
        name: 'Deploy with Helm'
        run: |
            cd ./frontend/helm-chart && \
            export TIMESTAMP=$(date +%s) && \
            helm upgrade -i --force utn-ads-2021-frontend -f values.yaml \
            --set-string timestamp=$TIMESTAMP \
            ./
         
  backend:
    runs-on: self-hosted
    permissions:
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders-b
      - 
        name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders-b
      -
        name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/greedhub/utn-ads-2021-backend:latest
          context: ./backend
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        name: Install Helm
        uses: azure/setup-helm@v1
        id: install
        with:
          version: 3.1.3
      - 
        name: 'Apply Kubeconfig'
        run: mkdir -p $HOME/.kube && echo ${{ secrets.KUBECONFIG }} | base64 -d > $HOME/.kube/config 
      -
        name: 'Deploy with Helm'
        run: |
            cd ./backend/helm-chart && \
            export TIMESTAMP=$(date +%s) && \
            helm upgrade -i --force utn-ads-2021-backend -f values.yaml \
            --set-string timestamp=$TIMESTAMP \
            --set-string mongoUrl=${{ secrets.BACKEND_MONGO_URL }} \
            --set-string access_token.secret=${{ secrets.BACKEND_ATOKEN_SECRET }} \
            --set-string refresh_token.secret=${{ secrets.BACKEND_RTOKEN_SECRET }} \
            ./
  
  devices-controller:
    runs-on: self-hosted
    permissions:
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders-d
      - 
        name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders-d
      -
        name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/greedhub/utn-ads-2021-devices-controller:latest
          context: ./devicesController
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        name: Install Helm
        uses: azure/setup-helm@v1
        id: install
        with:
          version: 3.1.3
      - 
        name: 'Apply Kubeconfig'
        run: mkdir -p $HOME/.kube && echo ${{ secrets.KUBECONFIG }} | base64 -d > $HOME/.kube/config 
      -
        name: 'Deploy with Helm'
        run: |
            cd ./devicesController/helm-chart && \
            export TIMESTAMP=$(date +%s) && \
            helm upgrade -i --force utn-ads-2021-devices -f values.yaml \
            --set-string mqtt.username=${{ secrets.MQTT_USER }} \
            --set-string mqtt.password=${{ secrets.MQTT_PASS }} \
            --set-string mqtt.caCert=${{ secrets.MQTT_CA }} \
            --set-string mqtt.clientCert=${{ secrets.MQTT_CLIENT_CERT }} \
            --set-string mqtt.clientKey=${{ secrets.MQTT_CLIENT_KEY }} \
            --set-string timestamp=$TIMESTAMP \
            ./